(MODULES-11458) Revert deferred function
puppetlabs/puppetlabs-accounts pull request #490
Opened 2024-07-24 12:24 UTC by Ramesh7

## Summary

Revert deferred function

## Additional Context
Add any additional context about the problem here. 
- [ ] Root cause and the steps to reproduce. (If applicable)
- [ ] Thought process behind the implementation.

## Related Issues (if any)
Mention any related issues or pull requests.

## Checklist
- [ ] 🟢 Spec tests.
- [ ] 🟢 Acceptance tests.
- [ ] Manually verified. (For example `puppet apply`)

2024-07-24 12:58 UTC, bastelfreak requested changes
Can you please explain why this gets reverted?

2024-07-25 04:21 UTC, Ramesh7 commented on lib/puppet/functions/user_password.rb
> -    password
yeah, it returns as it is. 
We have implemented based on earlier understanding and handover but I feel probably we are missing something here. That is one reason I am reverting.

Also there is customer reported issue where `/etc/shadow` is getting populting with `"Deferred({'name' => 'user_password', 'argume...` content.

2024-08-09 17:15 UTC, peelman commented on lib/puppet/functions/user_password.rb
> -    password
I am having this exact issue currently after updating the accounts module.  Rolling back in our environment until this is fixed.

```
cat /etc/shadow
...
admin:Deferred({'name' => 'user_password', 'arguments' => ['$6$OLbl..snip..gPrlY.']}):19943:0:99999:7:::
...
```

2024-08-13 09:17 UTC, bastelfreak approved these changes
the function isn't properly implemented, it only returns the password as plaintext. so I think it makes sense to revert this.

2024-08-13 09:32 UTC, merged